# Generated by Django 5.2 on 2025-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
