# Generated by Django 5.2.1 on 2025-05-12 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
