# Generated by Django 5.2.1 on 2025-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_data_nasc_cliente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=0, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
